### ISSUE TITLE
Backwards Compatibility

### ISSUE THREAD

**Issue by TheMrIron2** [SertexTeam/FireCast#2]
We could pretty easily just clean this project up and release it because it's basically complete - but I'm not familiar enough with the file structure and makeup of FireBox files to make backwards compatibility, which could be a huge selling point in future. If someone (cough Ale) could spend a few minutes to make it run FireBox disks out of the box, that would be great.

**Comment by Ale32bit** [comment]
FireCast is abandoned, just like all other Sertex projects
